<?php

namespace Database\Seeders;

use App\Models\Roles;
use App\Models\Subscriptions;
use App\Models\Icon; // Asegúrate de que tu modelo Icon se llama así
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // Seeder para Roles
        Roles::factory()->create([
            'name' => 'Administrador',
            'description' => 'Administrador del sistema',
        ]);
        Roles::factory()->create([
            'name' => 'Cliente',
            'description' => 'Usuario del sistema',
        ]);
        Roles::factory()->create([
            'name' => 'Ventas',
            'description' => 'Usuario de ventas del sistema',
        ]);
       
        // Seeder para Subscriptions
        Subscriptions::factory()->create([
            'name' => 'Plan Premium',
            'description' => '<li>Artículos de inventario – <strong>600</strong></li> <strong></strong>
                            <li>Usuarios – <strong>4</strong></li>',
            'cantUsers' => 4,
            'cantItems' => 600,
        ]);
        Subscriptions::factory()->create([
            'name' => 'Plan Basico',
            'description' => '<li>Artículos de inventario – <strong>300</strong></li>
                            <li>Usuarios – <strong>2</strong></li>',
            'cantUsers' => 2,
            'cantItems' => 300,
        ]);
        Subscriptions::factory()->create([
            'name' => 'Plan Prueba de 7 dias',
            'description' => '<li>Artículos de inventario – <strong>30</strong></li>
                            <li>Usuarios – <strong>2</strong></li>',
            'cantUsers' => 2,
            'cantItems' => 30,
        ]);

        // ---

        // Seeder para Icons
        Icon::insert([
            ['id' => 1, 'name' => 'Cara sonriente', 'value' => '😀'],
            ['id' => 2, 'name' => 'Cara feliz con ojos sonrientes', 'value' => '😁'],
            ['id' => 3, 'name' => 'Cara con lágrimas de alegría', 'value' => '😂'],
            ['id' => 4, 'name' => 'Cara rodando por el suelo de risa', 'value' => '🤣'],
            ['id' => 5, 'name' => 'Cara sonriente con boca abierta y ojos sonrientes', 'value' => '🤩'],
            ['id' => 6, 'name' => 'Cara lanzando un beso', 'value' => '😘'],
            ['id' => 7, 'name' => 'Cara sonriente con ojos de corazón', 'value' => '😍'],
            ['id' => 8, 'name' => 'Cara besando', 'value' => '😚'],
            ['id' => 9, 'name' => 'Cara sonriente con sudor', 'value' => '😅'],
            ['id' => 10, 'name' => 'Cara sonriente con aura', 'value' => '😇'],
            ['id' => 11, 'name' => 'Cara sonriente con boca abierta', 'value' => '😃'],
            ['id' => 12, 'name' => 'Cara sonriente', 'value' => '🙂'],
            ['id' => 13, 'name' => 'Cara de sorpresa', 'value' => '😮'],
            ['id' => 14, 'name' => 'Cara en blanco', 'value' => '😐'],
            ['id' => 15, 'name' => 'Cara sin expresión', 'value' => '😑'],
            ['id' => 16, 'name' => 'Cara pensante', 'value' => '🤔'],
            ['id' => 17, 'name' => 'Cara neutral', 'value' => '😐'],
            ['id' => 18, 'name' => 'Cara con cierre de cremallera en la boca', 'value' => '🤐'],
            ['id' => 19, 'name' => 'Cara con cabeza explosiva', 'value' => '🤯'],
            ['id' => 20, 'name' => 'Cara asustada', 'value' => '😱'],
            ['id' => 21, 'name' => 'Cara preocupada', 'value' => '😟'],
            ['id' => 22, 'name' => 'Cara triste pero aliviada', 'value' => '😥'],
            ['id' => 23, 'name' => 'Cara triste', 'value' => '😔'],
            ['id' => 24, 'name' => 'Cara llorando', 'value' => '😢'],
            ['id' => 25, 'name' => 'Cara de angustia', 'value' => '😩'],
            ['id' => 26, 'name' => 'Cara cansada', 'value' => '😫'],
            ['id' => 27, 'name' => 'Cara enojada', 'value' => '😡'],
            ['id' => 28, 'name' => 'Cara con símbolos en la boca', 'value' => '🤬'],
            ['id' => 29, 'name' => 'Cara con vapor por la nariz', 'value' => '😤'],
            ['id' => 30, 'name' => 'Cara de diablillo', 'value' => '👿'],
            ['id' => 31, 'name' => 'Cara de ogro', 'value' => '👹'],
            ['id' => 32, 'name' => 'Calavera', 'value' => '💀'],
            ['id' => 33, 'name' => 'Fantasma', 'value' => '👻'],
            ['id' => 34, 'name' => 'Monstruo de la galleta', 'value' => '🍪'],
            ['id' => 35, 'name' => 'Caca sonriente', 'value' => '💩'],
            ['id' => 36, 'name' => 'Payaso', 'value' => '🤡'],
            ['id' => 37, 'name' => 'Gato sonriente', 'value' => '😺'],
            ['id' => 38, 'name' => 'Gato con ojos de corazón', 'value' => '😻'],
            ['id' => 39, 'name' => 'Gato llorando', 'value' => '😿'],
            ['id' => 40, 'name' => 'Mono que no ve el mal', 'value' => '🙈'],
            ['id' => 41, 'name' => 'Mono que no oye el mal', 'value' => '🙉'],
            ['id' => 42, 'name' => 'Mono que no habla el mal', 'value' => '🙊'],
            ['id' => 43, 'name' => 'Bebé', 'value' => '👶'],
            ['id' => 44, 'name' => 'Niño', 'value' => '🧒'],
            ['id' => 45, 'name' => 'Hombre', 'value' => '👨'],
            ['id' => 46, 'name' => 'Mujer', 'value' => '👩'],
            ['id' => 47, 'name' => 'Persona mayor', 'value' => '👴'],
            ['id' => 48, 'name' => 'Hombre con turbante', 'value' => '👳‍♂️'],
            ['id' => 49, 'name' => 'Princesa', 'value' => '👸'],
            ['id' => 50, 'name' => 'Persona con sombrero de chef', 'value' => '👨‍🍳'],
            ['id' => 51, 'name' => 'Doctor', 'value' => '👨‍⚕️'],
            ['id' => 52, 'name' => 'Bombero', 'value' => '👨‍🚒'],
            ['id' => 53, 'name' => 'Policía', 'value' => '👮‍♂️'],
            ['id' => 54, 'name' => 'Granjero', 'value' => '👨‍🌾'],
            ['id' => 55, 'name' => 'Estudiante', 'value' => '👨‍🎓'],
            ['id' => 56, 'name' => 'Cantante', 'value' => '🎤'],
            ['id' => 57, 'name' => 'Artista', 'value' => '🎨'],
            ['id' => 58, 'name' => 'Atleta', 'value' => '🏃‍♂️'],
            ['id' => 59, 'name' => 'Persona bailando', 'value' => '💃'],
            ['id' => 60, 'name' => 'Mano levantada', 'value' => '✋'],
            ['id' => 61, 'name' => 'Pulgar hacia arriba', 'value' => '👍'],
            ['id' => 62, 'name' => 'Pulgar hacia abajo', 'value' => '👎'],
            ['id' => 63, 'name' => 'Signo de victoria', 'value' => '✌️'],
            ['id' => 64, 'name' => 'Puño levantado', 'value' => '✊'],
            ['id' => 65, 'name' => 'Rezo', 'value' => '🙏'],
            ['id' => 66, 'name' => 'Músculo', 'value' => '💪'],
            ['id' => 67, 'name' => 'Aplauso', 'value' => '👏'],
            ['id' => 68, 'name' => 'Saludo militar', 'value' => '🫡'],
            ['id' => 69, 'name' => 'Corazón rojo', 'value' => '❤️'],
            ['id' => 70, 'name' => 'Corazón morado', 'value' => '💜'],
            ['id' => 71, 'name' => 'Corazón azul', 'value' => '💙'],
            ['id' => 72, 'name' => 'Corazón verde', 'value' => '💚'],
            ['id' => 73, 'name' => 'Corazón amarillo', 'value' => '💛'],
            ['id' => 74, 'name' => 'Corazón naranja', 'value' => '🧡'],
            ['id' => 75, 'name' => 'Corazón roto', 'value' => '💔'],
            ['id' => 76, 'name' => 'Fuego', 'value' => '🔥'],
            ['id' => 77, 'name' => 'Estrella', 'value' => '⭐'],
            ['id' => 78, 'name' => 'Chispa', 'value' => '✨'],
            ['id' => 79, 'name' => 'Destello', 'value' => '💫'],
            ['id' => 80, 'name' => 'Sol', 'value' => '☀️'],
            ['id' => 81, 'name' => 'Nube', 'value' => '☁️'],
            ['id' => 82, 'name' => 'Lluvia', 'value' => '🌧️'],
            ['id' => 83, 'name' => 'Trueno', 'value' => '⛈️'],
            ['id' => 84, 'name' => 'Nieve', 'value' => '❄️'],
            ['id' => 85, 'name' => 'Luna creciente', 'value' => '🌙'],
            ['id' => 86, 'name' => 'Tierra', 'value' => '🌍'],
            ['id' => 87, 'name' => 'Volcán', 'value' => '🌋'],
            ['id' => 88, 'name' => 'Montaña', 'value' => '⛰️'],
            ['id' => 89, 'name' => 'Planta', 'value' => '🌱'],
            ['id' => 90, 'name' => 'Árbol', 'value' => '🌳'],
            ['id' => 91, 'name' => 'Cactus', 'value' => '🌵'],
            ['id' => 92, 'name' => 'Flor', 'value' => '🌸'],
            ['id' => 93, 'name' => 'Rosa', 'value' => '🌹'],
            ['id' => 94, 'name' => 'Girasol', 'value' => '🌻'],
            ['id' => 95, 'name' => 'Trébol', 'value' => '🍀'],
            ['id' => 96, 'name' => 'Hoja', 'value' => '🍃'],
            ['id' => 97, 'name' => 'Hongo', 'value' => '🍄'],
            ['id' => 98, 'name' => 'Uva', 'value' => '🍇'],
            ['id' => 99, 'name' => 'Manzana', 'value' => '🍎'],
            ['id' => 100, 'name' => 'Naranja', 'value' => '🍊'],
            ['id' => 101, 'name' => 'Limón', 'value' => '🍋'],
            ['id' => 102, 'name' => 'Plátano', 'value' => '🍌'],
            ['id' => 103, 'name' => 'Sandía', 'value' => '🍉'],
            ['id' => 104, 'name' => 'Fresa', 'value' => '🍓'],
            ['id' => 105, 'name' => 'Cereza', 'value' => '🍒'],
            ['id' => 106, 'name' => 'Piña', 'value' => '🍍'],
            ['id' => 107, 'name' => 'Coco', 'value' => '🥥'],
            ['id' => 108, 'name' => 'Maíz', 'value' => '🌽'],
            ['id' => 109, 'name' => 'Pimiento', 'value' => '🌶️'],
            ['id' => 110, 'name' => 'Patata', 'value' => '🥔'],
            ['id' => 111, 'name' => 'Tomate', 'value' => '🍅'],
            ['id' => 112, 'name' => 'Pan', 'value' => '🍞'],
            ['id' => 113, 'name' => 'Queso', 'value' => '🧀'],
            ['id' => 114, 'name' => 'Huevo', 'value' => '🥚'],
            ['id' => 115, 'name' => 'Carne', 'value' => '🍖'],
            ['id' => 116, 'name' => 'Pollo', 'value' => '🍗'],
            ['id' => 117, 'name' => 'Pescado', 'value' => '🐟'],
            ['id' => 118, 'name' => 'Sushi', 'value' => '🍣'],
            ['id' => 119, 'name' => 'Pizza', 'value' => '🍕'],
            ['id' => 120, 'name' => 'Hamburguesa', 'value' => '🍔'],
            ['id' => 121, 'name' => 'Papas fritas', 'value' => '🍟'],
            ['id' => 122, 'name' => 'Perro caliente', 'value' => '🌭'],
            ['id' => 123, 'name' => 'Taco', 'value' => '🌮'],
            ['id' => 124, 'name' => 'Burrito', 'value' => '🌯'],
            ['id' => 125, 'name' => 'Palomitas de maíz', 'value' => '🍿'],
            ['id' => 126, 'name' => 'Dona', 'value' => '🍩'],
            ['id' => 127, 'name' => 'Helado', 'value' => '🍦'],
            ['id' => 128, 'name' => 'Pastel', 'value' => '🎂'],
            ['id' => 129, 'name' => 'Galleta', 'value' => '🍪'],
            ['id' => 130, 'name' => 'Chocolate', 'value' => '🍫'],
            ['id' => 131, 'name' => 'Caramelo', 'value' => '🍬'],
            ['id' => 132, 'name' => 'Miel', 'value' => '🍯'],
            ['id' => 133, 'name' => 'Café', 'value' => '☕'],
            ['id' => 134, 'name' => 'Té', 'value' => '🍵'],
            ['id' => 135, 'name' => 'Cerveza', 'value' => '🍺'],
            ['id' => 136, 'name' => 'Vino', 'value' => '🍷'],
            ['id' => 137, 'name' => 'Cóctel', 'value' => '🍸'],
            ['id' => 138, 'name' => 'Agua', 'value' => '💧'],
            ['id' => 139, 'name' => 'Libro', 'value' => '📖'],
            ['id' => 140, 'name' => 'Lápiz', 'value' => '✏️'],
            ['id' => 141, 'name' => 'Tijeras', 'value' => '✂️'],
            ['id' => 142, 'name' => 'Teléfono', 'value' => '📱'],
            ['id' => 143, 'name' => 'Computadora', 'value' => '💻'],
            ['id' => 144, 'name' => 'Ratón de computadora', 'value' => '🖱️'],
            ['id' => 145, 'name' => 'Teclado', 'value' => '⌨️'],
            ['id' => 146, 'name' => 'Impresora', 'value' => '🖨️'],
            ['id' => 147, 'name' => 'Cámara', 'value' => '📸'],
            ['id' => 148, 'name' => 'Videojuego', 'value' => '🎮'],
            ['id' => 149, 'name' => 'Micrófono', 'value' => '🎤'],
            ['id' => 150, 'name' => 'Auriculares', 'value' => '🎧'],
            ['id' => 151, 'name' => 'Radio', 'value' => '📻'],
            ['id' => 152, 'name' => 'Televisión', 'value' => '📺'],
            ['id' => 153, 'name' => 'Película', 'value' => '🎬'],
            ['id' => 154, 'name' => 'Bolsa de dinero', 'value' => '💰'],
            ['id' => 155, 'name' => 'Tarjeta de crédito', 'value' => '💳'],
            ['id' => 156, 'name' => 'Bomba', 'value' => '💣'],
            ['id' => 157, 'name' => 'Pistola', 'value' => '🔫'],
            ['id' => 158, 'name' => 'Cuchillo', 'value' => '🔪'],
            ['id' => 159, 'name' => 'Jeringa', 'value' => '💉'],
            ['id' => 160, 'name' => 'Pastilla', 'value' => '💊'],
            ['id' => 161, 'name' => 'Coche', 'value' => '🚗'],
            ['id' => 162, 'name' => 'Taxi', 'value' => '🚕'],
            ['id' => 163, 'name' => 'Autobús', 'value' => '🚌'],
            ['id' => 164, 'name' => 'Tren', 'value' => '🚂'],
            ['id' => 165, 'name' => 'Avión', 'value' => '✈️'],
            ['id' => 166, 'name' => 'Bicicleta', 'value' => '🚲'],
            ['id' => 167, 'name' => 'Barco', 'value' => '⛵'],
            ['id' => 168, 'name' => 'Cohete', 'value' => '🚀'],
            ['id' => 169, 'name' => 'Semáforo', 'value' => '🚦'],
            ['id' => 170, 'name' => 'Señal de stop', 'value' => '🛑'],
            ['id' => 171, 'name' => 'Ancla', 'value' => '⚓'],
            ['id' => 172, 'name' => 'Reloj', 'value' => '⏰'],
            ['id' => 173, 'name' => 'Reloj de arena', 'value' => '⏳'],
            ['id' => 174, 'name' => 'Calendario', 'value' => '📅'],
            ['id' => 175, 'name' => 'Bolsa', 'value' => '👜'],
            ['id' => 176, 'name' => 'Zapatos', 'value' => '👟'],
            ['id' => 177, 'name' => 'Anillo', 'value' => '💍'],
            ['id' => 178, 'name' => 'Corona', 'value' => '👑'],
            ['id' => 179, 'name' => 'Diamante', 'value' => '💎'],
            ['id' => 180, 'name' => 'Balón de fútbol', 'value' => '⚽'],
            ['id' => 181, 'name' => 'Balón de baloncesto', 'value' => '🏀'],
            ['id' => 182, 'name' => 'Balón de béisbol', 'value' => '⚾'],
            ['id' => 183, 'name' => 'Balón de voleibol', 'value' => '🏐'],
            ['id' => 184, 'name' => 'Raqueta de tenis', 'value' => '🎾'],
            ['id' => 185, 'name' => 'Bolos', 'value' => '🎳'],
            ['id' => 186, 'name' => 'Golf', 'value' => '⛳'],
            ['id' => 187, 'name' => 'Pesas', 'value' => '🏋️'],
            ['id' => 188, 'name' => 'Copa', 'value' => '🏆'],
            ['id' => 189, 'name' => 'Medalla', 'value' => '🏅'],
            ['id' => 190, 'name' => 'Guitarra', 'value' => '🎸'],
            ['id' => 191, 'name' => 'Piano', 'value' => '🎹'],
            ['id' => 192, 'name' => 'Violín', 'value' => '🎻'],
            ['id' => 193, 'name' => 'Trompeta', 'value' => '🎺'],
            ['id' => 194, 'name' => 'Tambor', 'value' => '🥁'],
            ['id' => 195, 'name' => 'Perro', 'value' => '🐶'],
            ['id' => 196, 'name' => 'Gato', 'value' => '🐱'],
            ['id' => 197, 'name' => 'Ratón', 'value' => '🐭'],
            ['id' => 198, 'name' => 'Hámster', 'value' => '🐹'],
            ['id' => 199, 'name' => 'Conejo', 'value' => '🐰'],
            ['id' => 200, 'name' => 'Zorro', 'value' => '🦊'],
            ['id' => 201, 'name' => 'Oso', 'value' => '🐻'],
            ['id' => 202, 'name' => 'Panda', 'value' => '🐼'],
            ['id' => 203, 'name' => 'Koala', 'value' => '🐨'],
            ['id' => 204, 'name' => 'Tigre', 'value' => '🐯'],
            ['id' => 205, 'name' => 'León', 'value' => '🦁'],
            ['id' => 206, 'name' => 'Cebra', 'value' => '🦓'],
            ['id' => 207, 'name' => 'Caballo', 'value' => '🐴'],
            ['id' => 208, 'name' => 'Vaca', 'value' => '🐮'],
            ['id' => 209, 'name' => 'Cerdo', 'value' => '🐷'],
            ['id' => 210, 'name' => 'Jabalí', 'value' => '🐗'],
            ['id' => 211, 'name' => 'Oveja', 'value' => '🐑'],
            ['id' => 212, 'name' => 'Cabra', 'value' => '🐐'],
            ['id' => 213, 'name' => 'Camello', 'value' => '🐪'],
            ['id' => 214, 'name' => 'Delfín', 'value' => '🐬'],
            ['id' => 215, 'name' => 'Ballena', 'value' => '🐳'],
            ['id' => 216, 'name' => 'Pez', 'value' => '🐠'],
            ['id' => 217, 'name' => 'Pulpo', 'value' => '🐙'],
            ['id' => 218, 'name' => 'Cangrejo', 'value' => '🦀'],
            ['id' => 219, 'name' => 'Camarón', 'value' => '🦐'],
            ['id' => 220, 'name' => 'Caracol', 'value' => '🐌'],
            ['id' => 221, 'name' => 'Mariposa', 'value' => '🦋'],
            ['id' => 222, 'name' => 'Mariquita', 'value' => '🐞'],
            ['id' => 223, 'name' => 'Abeja', 'value' => '🐝'],
            ['id' => 224, 'name' => 'Hormiga', 'value' => '🐜'],
            ['id' => 225, 'name' => 'Serpiente', 'value' => '🐍'],
            ['id' => 226, 'name' => 'Cocodrilo', 'value' => '🐊'],
            ['id' => 227, 'name' => 'Tortuga', 'value' => '🐢'],
            ['id' => 228, 'name' => 'Lagarto', 'value' => '🦎'],
            ['id' => 229, 'name' => 'Pájaro', 'value' => '🐦'],
            ['id' => 230, 'name' => 'Búho', 'value' => '🦉'],
            ['id' => 231, 'name' => 'Pollito', 'value' => '🐥'],
            ['id' => 232, 'name' => 'Pavo', 'value' => '🦃'],
            ['id' => 233, 'name' => 'Gallina', 'value' => '🐔'],
            ['id' => 234, 'name' => 'Pingüino', 'value' => '🐧'],
            ['id' => 235, 'name' => 'Cisne', 'value' => '🦢'],
            ['id' => 236, 'name' => 'Pato', 'value' => '🦆'],
            ['id' => 237, 'name' => 'Águila', 'value' => '🦅'],
            ['id' => 238, 'name' => 'Murciélago', 'value' => '🦇'],
            ['id' => 239, 'name' => 'Araña', 'value' => '🕷️'],
            ['id' => 240, 'name' => 'Telaraña', 'value' => '🕸️'],
            ['id' => 241, 'name' => 'Árbol de Navidad', 'value' => '🎄'],
            ['id' => 242, 'name' => 'Regalo', 'value' => '🎁'],
            ['id' => 243, 'name' => 'Globo', 'value' => '🎈'],
            ['id' => 244, 'name' => 'Confeti', 'value' => '🎉'],
            ['id' => 245, 'name' => 'Vela', 'value' => '🕯️'],
            ['id' => 246, 'name' => 'Anillo de compromiso', 'value' => '💍'],
            ['id' => 247, 'name' => 'Diamante', 'value' => '💎'],
            ['id' => 248, 'name' => 'Corona', 'value' => '👑'],
            ['id' => 249, 'name' => 'Vestido', 'value' => '👗'],
            ['id' => 250, 'name' => 'Camisa', 'value' => '👕'],
            ['id' => 251, 'name' => 'Pantalón', 'value' => '👖'],
            ['id' => 252, 'name' => 'Zapatos', 'value' => '👟'],
            ['id' => 253, 'name' => 'Gafas de sol', 'value' => '😎'],
            ['id' => 254, 'name' => 'Sombrero', 'value' => '🎩'],
            ['id' => 255, 'name' => 'Paraguas', 'value' => '☂️'],
            ['id' => 256, 'name' => 'Bolso', 'value' => '👜'],
            ['id' => 257, 'name' => 'Mochila', 'value' => '🎒'],
            ['id' => 258, 'name' => 'Maleta', 'value' => '💼'],
            ['id' => 259, 'name' => 'Billetera', 'value' => '👛'],
            ['id' => 260, 'name' => 'Llave', 'value' => '🔑'],
            ['id' => 261, 'name' => 'Candado', 'value' => '🔒'],
            ['id' => 262, 'name' => 'Bombilla', 'value' => '💡'],
            ['id' => 263, 'name' => 'Cuchara', 'value' => '🥄'],
            ['id' => 264, 'name' => 'Tenedor', 'value' => '🍴'],
            ['id' => 265, 'name' => 'Cuchillo', 'value' => '🔪'],
            ['id' => 266, 'name' => 'Plato', 'value' => '🍽️'],
            ['id' => 267, 'name' => 'Taza', 'value' => '☕'],
            ['id' => 268, 'name' => 'Botella', 'value' => '🍾'],
            ['id' => 269, 'name' => 'Martillo', 'value' => '🔨'],
            ['id' => 270, 'name' => 'Clavo', 'value' => '🔩'],
            ['id' => 271, 'name' => 'Taladro', 'value' => ' ड्रिल'],
            ['id' => 272, 'name' => 'Destornillador', 'value' => '螺丝刀'],
            ['id' => 273, 'name' => 'Llave inglesa', 'value' => '扳手'],
            ['id' => 274, 'name' => 'Sierra', 'value' => '锯子'],
            ['id' => 275, 'name' => 'Bomba de gasolina', 'value' => '⛽'],
            ['id' => 276, 'name' => 'Señal de tráfico', 'value' => '🚦'],
            ['id' => 277, 'name' => 'Ancla', 'value' => '⚓'],
            ['id' => 278, 'name' => 'Timón', 'value' => '舵'],
            ['id' => 279, 'name' => 'Faro', 'value' => '灯塔'],
            ['id' => 280, 'name' => 'Mapa', 'value' => '🗺️'],
            ['id' => 281, 'name' => 'Brújula', 'value' => '🧭'],
            ['id' => 282, 'name' => 'Telescopio', 'value' => '🔭'],
            ['id' => 283, 'name' => 'Microscopio', 'value' => '🔬'],
            ['id' => 284, 'name' => 'ADN', 'value' => '🧬'],
            ['id' => 285, 'name' => 'Placa de Petri', 'value' => '🧫'],
            ['id' => 286, 'name' => 'Probeta', 'value' => '🧪'],
            ['id' => 287, 'name' => 'Tubo de ensayo', 'value' => '试管'],
            ['id' => 288, 'name' => 'Balón de fútbol americano', 'value' => '🏈'],
            ['id' => 289, 'name' => 'Pelota de rugby', 'value' => '🏉'],
            ['id' => 290, 'name' => 'Pelota de tenis de mesa', 'value' => '🏓'],
            ['id' => 291, 'name' => 'Bádminton', 'value' => '🏸'],
            ['id' => 292, 'name' => 'Hockey sobre hielo', 'value' => '🏒'],
            ['id' => 293, 'name' => 'Hockey sobre hierba', 'value' => '🏑'],
            ['id' => 294, 'name' => 'Cricket', 'value' => '🏏'],
            ['id' => 295, 'name' => 'Arco y flecha', 'value' => '🏹'],
            ['id' => 296, 'name' => 'Caña de pescar', 'value' => '🎣'],
            ['id' => 297, 'name' => 'Guante de boxeo', 'value' => '🥊'],
            ['id' => 298, 'name' => 'Kimono de judo', 'value' => '🥋'],
            ['id' => 299, 'name' => 'Esquí', 'value' => '⛷️'],
            ['id' => 300, 'name' => 'Snowboard', 'value' => '🏂'],
            ['id' => 301, 'name' => 'Patinaje sobre hielo', 'value' => '⛸️'],
            ['id' => 302, 'name' => 'Patinaje sobre ruedas', 'value' => '🛼'],
            ['id' => 303, 'name' => 'Buceo', 'value' => '🤿'],
            ['id' => 304, 'name' => 'Natación', 'value' => '🏊'],
            ['id' => 305, 'name' => 'Surf', 'value' => '🏄'],
            ['id' => 306, 'name' => 'Remo', 'value' => '🚣'],
            ['id' => 307, 'name' => 'Montañismo', 'value' => '🧗'],
            ['id' => 308, 'name' => 'Pesa rusa', 'value' => ' Kettlebell'],
            ['id' => 309, 'name' => 'Balón de ejercicio', 'value' => ' Exercise Ball'],
            ['id' => 310, 'name' => 'Raqueta de ping-pong', 'value' => '🏓'],
            ['id' => 311, 'name' => 'Red de voleibol', 'value' => '🏐'],
            ['id' => 312, 'name' => 'Red de fútbol', 'value' => '🥅'],
            ['id' => 313, 'name' => 'Bate de béisbol', 'value' => '⚾'],
            ['id' => 314, 'name' => 'Guante de béisbol', 'value' => '🥎'],
            ['id' => 315, 'name' => 'Guante de boxeo', 'value' => '🥊'],
            ['id' => 316, 'name' => 'Máscara de buceo', 'value' => '🤿'],
            ['id' => 317, 'name' => 'Aletas de natación', 'value' => '🤿'],
            ['id' => 318, 'name' => 'Gafas de natación', 'value' => '🏊‍♀️'],
            ['id' => 319, 'name' => 'Tablero de surf', 'value' => '🏄‍♀️'],
            ['id' => 320, 'name' => 'Remo de bote', 'value' => '🚣‍♀️'],
            ['id' => 321, 'name' => 'Casco de bicicleta', 'value' => '🚴‍♂️'],
            ['id' => 322, 'name' => 'Gafas de esquí', 'value' => '⛷️'],
            ['id' => 323, 'name' => 'Gorro de esquí', 'value' => '🎿'],
            ['id' => 324, 'name' => 'Raqueta de bádminton', 'value' => '🏸'],
            ['id' => 325, 'name' => 'Volante de bádminton', 'value' => ' shuttlecock'],
            ['id' => 326, 'name' => 'Paleta de tenis de mesa', 'value' => '🏓'],
            ['id' => 327, 'name' => 'Taco de billar', 'value' => '🎱'],
            ['id' => 328, 'name' => 'Dardos', 'value' => '🎯'],
            ['id' => 329, 'name' => 'Juego de mesa', 'value' => '🎲'],
            ['id' => 330, 'name' => 'Carta de juego', 'value' => '🃏'],
            ['id' => 331, 'name' => 'Fichas de póker', 'value' => ' poker chips'],
            ['id' => 332, 'name' => 'Baraja de cartas', 'value' => ' deck of cards'],
            ['id' => 333, 'name' => 'Casino', 'value' => '🎰'],
            ['id' => 334, 'name' => 'Parque de atracciones', 'value' => '🎡'],
            ['id' => 335, 'name' => 'Circo', 'value' => '🎪'],
            ['id' => 336, 'name' => 'Máscara de teatro', 'value' => '🎭'],
            ['id' => 337, 'name' => 'Teatro', 'value' => '🏛️'],
            ['id' => 338, 'name' => 'Galería de arte', 'value' => '🖼️'],
            ['id' => 339, 'name' => 'Museo', 'value' => '🏛️'],
            ['id' => 340, 'name' => 'Bibliografía', 'value' => '📖'],
            ['id' => 341, 'name' => 'Globo terráqueo', 'value' => ' Globe showing Europe-Africa'],
            ['id' => 342, 'name' => 'Monumento', 'value' => ' Monuments'],
            ['id' => 343, 'name' => 'Torre Eiffel', 'value' => '🗼'],
            ['id' => 344, 'name' => 'Estatua de la Libertad', 'value' => '🗽'],
            ['id' => 345, 'name' => 'Pirámide', 'value' => ' pyramid'],
            ['id' => 346, 'name' => 'Puente', 'value' => '🌉'],
            ['id' => 347, 'name' => 'Castillo', 'value' => '🏰'],
            ['id' => 348, 'name' => 'Casa', 'value' => '🏠'],
            ['id' => 349, 'name' => 'Edificio', 'value' => '🏢'],
            ['id' => 350, 'name' => 'Escuela', 'value' => '🏫'],
            ['id' => 351, 'name' => 'Hospital', 'value' => '🏥']
        ]);
    }
}